document.write('<html>\n');
document.write('\n');
document.write('<head>\n');
document.write('<title>Simple Intuitive Gaming Library API</title>\n');
document.write('<link rel="stylesheet" type="text/css" href="./style.css" />\n');
document.write('</head>\n');
document.write('\n');
document.write('\n');
document.write('<body>\n');
document.write('\n');
document.write('<table cellpadding="0" cellspacing="0" border="0" >\n');
document.write('    <tr>\n');
document.write('        <td class="logo">\n');
document.write('            <img src="./logo.png" height=70> <br />\n');
document.write('            <b>SIGIL Documentation</b>\n');
document.write('        </td>\n');
document.write('        <td class="links">\n');
document.write('            ||&nbsp; <a href="../API.html">Index</a> &nbsp;||\n');
document.write('            <br />\n');
document.write('            <!--\n');
document.write('            These are just links to misc stuff. \n');
document.write('            -->\n');
document.write('            ||&nbsp;\n');
document.write('            <a href="http://www.pygame.org">Pygame Home</a>&nbsp;||&nbsp;\n');
document.write('            <br />\n');
document.write('            ||&nbsp;\n');
document.write('            <a href="http://code.google.com/p/pygame-camengine/">SIGIL Home</a>&nbsp;||&nbsp;\n');
document.write('            <a href="http://pygame.org/project-SIGIL-1716-2989.html">SIGIL PyGame Release</a>&nbsp;||&nbsp;\n');
document.write('            <a href="../documentation.txt">SIGIL Documentation</a>&nbsp;||\n');
document.write('            \n');
document.write('            <br />&nbsp;<br />            \n');
document.write('            <!--\n');
document.write('            These are the actuall API links\n');
document.write('            -->\n');
document.write('            ||&nbsp;\n');
document.write('            <a href="./sigil.html">Main Package(sigil)</a>&nbsp;||&nbsp;');
document.write('            <a href="./locals.html">Locals</a>&nbsp;||&nbsp; \n');
document.write('            <a href="./parsing.html">Parsing</a>&nbsp;||&nbsp; \n');
document.write('            <a href="./screen.html">Screen</a>&nbsp;||&nbsp; \n');
document.write('            <a href="./sprite.html">Sprite</a>&nbsp;||&nbsp; \n');
document.write('            <a href="./tools.html">Tools</a>&nbsp;||&nbsp; \n');
document.write('            <a href="./world.html">World</a>&nbsp;||&nbsp; \n');
document.write('            \n');
document.write('        </td>\n');
document.write('    </tr>\n');
document.write('</table>\n');
document.write('\n');
document.write('</body>\n');
document.write('\n');
document.write('</html>\n');
document.write('\n');
document.write('\n');